// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_token.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (user_id, token, expires_at, created_at, updated_at, revoked_at)
VALUES ($1, $2, $3, NOW(), NOW(), NULL)
RETURNING user_id, token, expires_at, created_at, updated_at, revoked_at
`

type CreateRefreshTokenParams struct {
	UserID    uuid.UUID    `json:"user_id"`
	Token     string       `json:"token"`
	ExpiresAt sql.NullTime `json:"expires_at"`
}

type CreateRefreshTokenRow struct {
	UserID    uuid.UUID    `json:"user_id"`
	Token     string       `json:"token"`
	ExpiresAt sql.NullTime `json:"expires_at"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	RevokedAt sql.NullTime `json:"revoked_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (CreateRefreshTokenRow, error) {
	row := q.queryRow(ctx, q.createRefreshTokenStmt, createRefreshToken, arg.UserID, arg.Token, arg.ExpiresAt)
	var i CreateRefreshTokenRow
	err := row.Scan(
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getRefreshTokenByToken = `-- name: GetRefreshTokenByToken :one
SELECT user_id, token, expires_at, created_at, updated_at, revoked_at
FROM refresh_tokens
WHERE token = $1
`

type GetRefreshTokenByTokenRow struct {
	UserID    uuid.UUID    `json:"user_id"`
	Token     string       `json:"token"`
	ExpiresAt sql.NullTime `json:"expires_at"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	RevokedAt sql.NullTime `json:"revoked_at"`
}

func (q *Queries) GetRefreshTokenByToken(ctx context.Context, token string) (GetRefreshTokenByTokenRow, error) {
	row := q.queryRow(ctx, q.getRefreshTokenByTokenStmt, getRefreshTokenByToken, token)
	var i GetRefreshTokenByTokenRow
	err := row.Scan(
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getRefreshTokenByUserId = `-- name: GetRefreshTokenByUserId :one
SELECT user_id, token, expires_at, created_at, updated_at, revoked_at
FROM refresh_tokens
WHERE user_id = $1
    AND revoked_at IS NULL
LIMIT 1
`

type GetRefreshTokenByUserIdRow struct {
	UserID    uuid.UUID    `json:"user_id"`
	Token     string       `json:"token"`
	ExpiresAt sql.NullTime `json:"expires_at"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	RevokedAt sql.NullTime `json:"revoked_at"`
}

func (q *Queries) GetRefreshTokenByUserId(ctx context.Context, userID uuid.UUID) (GetRefreshTokenByUserIdRow, error) {
	row := q.queryRow(ctx, q.getRefreshTokenByUserIdStmt, getRefreshTokenByUserId, userID)
	var i GetRefreshTokenByUserIdRow
	err := row.Scan(
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET revoked_at = NOW(), updated_at = NOW()
WHERE token = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, token string) error {
	_, err := q.exec(ctx, q.revokeRefreshTokenStmt, revokeRefreshToken, token)
	return err
}
